### ISSUE TITLE
WebM support

### ISSUE THREAD

**Issue by SnowGabe** [simonlindholm/toggle-gifs#23]
Like HTML5, WebM video is replacing GIF as a current web standard. The extension only supports GIF image, I'd love to see functionality also for WebM. If nothing will be done this addon has no use after some years.

**Comment by simonlindholm** [comment]
Yep, sounds reasonable. Only a question of me finding time for this addon, and of choosing a reasonable detection method for these kinds of videos (they aren't as standard as plain `<img>` tags, and most `<video>` elements come with controls attached).

**Comment by SnowGabe** [comment]
Have you made any progress?

**Comment by simonlindholm** [comment]
Sorry, no. Probably will take a few months until I get around to this (we'll see).

**Comment by LL25255252** [comment]
@SnowGabe 
For the meantime try Flash Control firefox addon. It blocks the autoplay.
https://addons.mozilla.org/en-us/firefox/addon/flash-control/

**Comment by SnowGabe** [comment]
I don't have Flash Player even installed, are you sure that addon is for me?
If Flash Control can control WebM autoplay what is the purpose of Toggle animated GIFs extension?

**Comment by simonlindholm** [comment]
Apparently it can control HTML5 video too. I can only imagine that it was a common feature request.

The purpose of the Toggle animated GIFs extension is, of course, to be able to control GIFs. ;)

**Comment by SnowGabe** [comment]
Yes, I thought that Flash Control also can handle GIFs.

**Comment by simonlindholm** [comment]
I added a bit of support in 309fbd8a8fd700f551effe1d825ce409b84b63ee. imgur, reddit w/ RES and gfycat are supported, and whatever other sites use `<video muted loop autoplay>`. More general WEBMs are not, since they probably supply their own controls and support for pausing them doesn't seem like it belongs in a GIF control addon.

http://simonsoftware.se/temp/toggle-gifs-gifv.xpi has an XPI, or you can build from source. Testing and feedback appreciated. In particular, bugs may have popped up due to the rewrite to support e10s (c8d50662e37d227bb23de419153f551b60868cb5).

**Comment by simonlindholm** [comment]
New version under review: https://addons.mozilla.org/en-US/firefox/addon/toggle-animated-gifs/versions/
