### ISSUE TITLE
Pause and Control+Pause do not work as hotkeys

### ISSUE THREAD

**Issue by alexolog** [simonlindholm/toggle-gifs#26]
see title

**Comment by alexolog** [comment]
see title

**Comment by simonlindholm** [comment]
Sorry for the late response, but, I don't quite understand what you mean?

**Comment by alexolog** [comment]
Sorry, something happened to the title.  Edited it

**Comment by alexolog** [comment]
Basically, if I set the hotkeys to be Pause and/or Ctrl+Pause, they don't work

**Comment by simonlindholm** [comment]
Ah. Maybe you fell for the automatic signed update? I didn't get around to making a release after merging your commit 792eac758765d32a367a95fd2b42bc0b88864590, due to lack of time, other changes, and not wanting to make the insane Mozilla addon review queues even longer...

I'm starting to hack a bit more on this addon again, though, so hopefully there'll be a new release at some point. Also it looks like the Pause key has finally gotten a `.key` property in Firefox Nightly, so it might also get resolved by itself. For now, do a local rebuild, or use http://simonsoftware.se/temp/toggle-gifs-e10s.xpi if you're comfortable with the "download XPIs from some random third-party server over http" thing. Includes some e10s fixes I'm working on.

**Comment by alexolog** [comment]
Nightly takes quite some time to get into production
I believe that I tried the code from the repository and the problem still persisted.  I will try the XPI you pointed to and report

**Comment by alexolog** [comment]
It works!

**Comment by simonlindholm** [comment]
Nice! Closing, since we already have #15.

(As far as I can tell, the `.key` property has the value "Pause" even as far back as Firefox 35. If you're on an old version, that would explain it.)

**Comment by alexolog** [comment]
No, I'm on the latest release version, just not comfortable running nightlies/alphas/betas.
Thanks!

**Comment by simonlindholm** [comment]
Odd. Could be a OS difference then (I'm on Linux).

**Comment by alexolog** [comment]
Still, the toggle-gifs-e10s.xpi works for me, so if the code makes it to the release version of toggle-gifs, everything is good

**Comment by simonlindholm** [comment]
New version under review: https://addons.mozilla.org/en-US/firefox/addon/toggle-animated-gifs/versions/
