### ISSUE TITLE
Behavior with direct links

### ISSUE THREAD

**Issue by 07416** [simonlindholm/toggle-gifs#39]
Some people might prefer autoplaying files when accessing direct links. Would help a lot with "image zoom" extensions, currently I have to always visit the site and manually start playing.

**Comment by reddit-is-fun** [comment]
@simonlindholm Do you get notified of new issues? Did I explain the issue poorly?

**Comment by simonlindholm** [comment]
I do, I just haven't had time to do anything with this extension lately.

It sounds like a valid request, even if I'm not sure know exactly to detect all the cases where autoplay would be wanted... For instance it's unclear how to distinguish images from the page from images overlaid by Thumbnail Zoom Plus. (Maybe it could be nice to just animate all dynamically added images according to some definition of that?)

When you say "direct links", I think of visiting .gif files directly, which could certainly be detected. I opened #6 for that a long time ago, but never got around to adding it because I felt that "animate on hover" was good enough and better in some respects.

**Comment by reddit-is-fun** [comment]
Support for direct links would help immensely, most of the videos and GIFs posted to websites like Reddit are direct links.
I enabled "auto-play on hover" setting, videos don't play when fetched with Mouseover Popup Image Viewer. They do when I disable Toggle animated GIFs extension.

**Comment by simonlindholm** [comment]
Yeah, "auto-play on hover" doesn't help with e.g. Mouseover Popup Image Viewer, nor would #6. That's because the image is not opened "directly" in any technical sense; rather, the addon sees a direct link and adds an element to the page which contains the image. This is mostly indistinguishable from if the page itself had included the image... From a less technical perspective the request makes more sense.

**Comment by 07416** [comment]
I had `media.autoplay.enabled` set to `false`, this caused the majority of the issues (most notably, being unable to view videos). Because GIF autoplay can be toggled with a shortcut I consider this request as insignificant and will close this issue.
